exclude:
  - README.md
baseurl: ""
menu:
  Resources: resources
  Tools and the IDE: tools
  Programming 101: programming
  CS Fundamentals: fundamentals
  Topics from Section: section
  More Topics: more
