exclude:
  - README.md
menu:
  Topics from Section: section
  Resource Guide: resources
  CS Fundamentals: fundamentals
  Programming 101: programming
  Tools and the IDE: tools
  More Topics: more
  For the Quiz: quiz
  Final Project: project
  Life After CS50: after
